# Generated by Django 6.0.6 on 2026-07-22 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa zespołu')),
                ('description', models.TextField(blank=True, help_text='Opcjonalny opis zakresu działań zespołu', null=True, verbose_name='Opis zespołu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('co_managers', models.ManyToManyField(blank=True, related_name='co_managed_teams', to=settings.AUTH_USER_MODEL, verbose_name='Współzarządzający')),
                ('head_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_managed_teams', to=settings.AUTH_USER_MODEL, verbose_name='Główny manager')),
            ],
            options={
                'verbose_name': 'Zespół',
                'verbose_name_plural': 'Zespoły',
                'ordering': ['name'],
            },
        ),
    ]
