# Generated by Django 6.0.6 on 2026-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Czy zespół jest aktywny. Odznaczenie oznacza miękkie usunięcie.', verbose_name='Aktywny'),
        ),
    ]
