# Generated by Django 6.0.6 on 2026-08-04 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='co_managers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='head_manager',
        ),
        migrations.AddField(
            model_name='team',
            name='hr',
            field=models.ForeignKey(blank=True, help_text='Osoba z HR przypisana do zespołu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_hr', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun HR'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(blank=True, help_text='Manager zarządzający zespołem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_manager', to=settings.AUTH_USER_MODEL, verbose_name='Manager zespołu'),
        ),
    ]
