# Generated by Django 6.0.6 on 2026-08-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_team_co_managers_remove_team_head_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis zespołu'),
        ),
        migrations.AlterField(
            model_name='team',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_team', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun HR'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy aktywny'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team', to=settings.AUTH_USER_MODEL, verbose_name='Manager zespołu'),
        ),
    ]
