# Generated by Django 6.0.6 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('COO', 'COO'), ('HR', 'HR'), ('Manager', 'Manager'), ('Worker', 'Worker')], max_length=20, null=True),
        ),
    ]
