# Generated by Django 6.0.6 on 2026-08-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Musi zmienić hasło przy pierwszym logowaniu'),
        ),
    ]
