# Generated by Django 6.0.6 on 2026-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Manager', 'Manager'), ('Worker', 'Worker')], max_length=20, null=True),
        ),
    ]
