# Generated by Django 6.0.4 on 2026-06-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerprofile',
            options={'verbose_name': 'Profil pracownika', 'verbose_name_plural': 'Profile pracowników'},
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data od')),
                ('end_date', models.DateField(verbose_name='Data do')),
                ('amount_days', models.PositiveIntegerField(verbose_name='Liczba dni roboczych')),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony'), ('canceled', 'Anulowany')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data złożenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
                ('who_confirmed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Potwierdził(a)')),
            ],
            options={
                'verbose_name': 'Wniosek urlopowy',
                'verbose_name_plural': 'Wnioski urlopowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
