# Generated by Django 6.0.6 on 2026-07-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_workerprofile_options_leaverequest'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='hire_date',
            field=models.DateField(verbose_name='Data zatrudnienia'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='other_experience_days',
            field=models.IntegerField(default=0, verbose_name='Wcześniejsze doświadczenie (dni)'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='other_experience_years',
            field=models.IntegerField(default=0, verbose_name='Wcześniejsze doświadczenie (lata)'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.team'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='used_leave_days',
            field=models.IntegerField(default=0, verbose_name='Wykorzystane dni urlopu'),
        ),
    ]
