# Generated by Django 6.0.6 on 2026-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_workerprofile_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='answer_comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Komentarz akceptującego'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='request_comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Komentarz pracownika'),
        ),
    ]
