# Generated by Django 6.0.6 on 2026-08-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leaverequest_answer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='answer_comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Komentarz odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='request_comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Komentarz wniosku'),
        ),
    ]
