# Generated by Django 6.0.6 on 2026-08-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_alter_leaverequest_answer_comment_and_more'),
        ('team', '0003_remove_team_co_managers_remove_team_head_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Zespół, do którego użytkownik należy jako pracownik', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.team', verbose_name='Zespół'),
        ),
    ]
