# Generated by Django 6.0.4 on 2026-05-12 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('dodaj', 'Dodaj'), ('usun', 'Usun'), ('edytuj', 'Edytuj'), ('zatwierdz', 'Zatwierdz'), ('odrzuc', 'Odrzuc'), ('anuluj', 'Anuluj'), ('reset_hasla', 'Reset_hasla')], max_length=20)),
                ('object_type', models.CharField(choices=[('user', 'User'), ('leave_request', 'Leave_request'), ('password', 'Password')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
