# Generated by Django 6.0.4 on 2026-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('dodaj', 'Dodaj'), ('usun', 'Usun'), ('edytuj', 'Edytuj'), ('zatwierdz', 'Zatwierdz'), ('odrzuc', 'Odrzuc'), ('anuluj', 'Anuluj'), ('reset_hasla', 'Reset_hasla'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login_failed'), ('403', 'Forbidden_403')], max_length=20),
        ),
    ]
