# Generated by Django 6.0.4 on 2026-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_changelog_ip_address_changelog_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='action',
            field=models.CharField(choices=[('dodaj', 'Dodaj'), ('usun', 'Usun'), ('edytuj', 'Edytuj'), ('zatwierdz', 'Zatwierdz'), ('odrzuc', 'Odrzuc'), ('anuluj', 'Anuluj'), ('reset_hasla', 'Reset_hasla'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login_failed'), ('403', 'Forbidden_403'), ('switch_choice', 'Switch_choice')], max_length=20),
        ),
    ]
