# Generated by Django 6.0.6 on 2026-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='invalidated',
            field=models.BooleanField(default=False, help_text="True gdy ten nieudany login zostal 'wyzerowany' przez pozniejsze udane logowanie."),
        ),
    ]
