# Generated by Django 6.0.6 on 2026-07-20 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Dodaj'), ('update', 'Edytuj'), ('approve', 'Zatwierdź'), ('reject', 'Odrzuć'), ('cancel', 'Anuluj'), ('delete', 'Usuń'), ('password_reset', 'Reset hasła'), ('new_account', 'Nowe Konto'), ('role_change', 'Zmiana roli')], max_length=20)),
                ('object_type', models.CharField(choices=[('user', 'Użytkownik'), ('leave_request', 'Wniosek urlopowy'), ('system_settings', 'Ustawienia systemu')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('login_success', 'Logowanie udane'), ('login_failed', 'Logowanie nieudane'), ('logout', 'Wylogowanie'), ('access_denied_403', 'Odmowa dostępu'), ('ip_locked', 'IP zablokowane')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Ostrzeżenie'), ('critical', 'Krytyczne')], default='info', max_length=10)),
                ('invalidated', models.BooleanField(default=False)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='who',
        ),
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='logs_logina_usernam_4d7451_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='logs_logina_ip_addr_129fa5_idx',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChangeLog',
        ),
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.RemoveField(
            model_name='loginattempt',
            name='user',
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['object_type', 'object_id'], name='logs_activi_object__9d046c_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['username', 'timestamp'], name='logs_authlo_usernam_fa5a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['ip_address', 'action', 'timestamp'], name='logs_authlo_ip_addr_aeef61_idx'),
        ),
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
