# Generated by Django 6.0.7 on 2026-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_activitylog_authlog_remove_changelog_who_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
