# Generated by Django 6.0.6 on 2026-07-23 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_activitylog_authlog_remove_changelog_who_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authlog',
            name='logs_authlo_usernam_fa5a0e_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Dodaj'), ('update', 'Edytuj'), ('approve', 'Zatwierdź'), ('reject', 'Odrzuć'), ('cancel', 'Anuluj'), ('delete', 'Usuń'), ('password_reset', 'Reset hasła'), ('new_account', 'Nowe Konto'), ('profile_assigned', 'Profil przypisany'), ('profile_updated', 'Profil zaktualizowany'), ('role_change', 'Zmiana roli')], max_length=20),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Logowanie udane'), ('login_failed', 'Logowanie nieudane'), ('incorrect_username', 'Brak użytkownika'), ('2fa_success', 'Weryfikacja 2FA udana'), ('2fa_failed', 'Niepoprawny kod 2FA'), ('logout', 'Wylogowanie'), ('access_denied_403', 'Odmowa dostępu'), ('ip_locked', 'IP zablokowane')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['user', 'timestamp'], name='logs_authlo_user_id_9f81f8_idx'),
        ),
        migrations.RemoveField(
            model_name='authlog',
            name='username',
        ),
    ]
