# Generated by Django 6.0.6 on 2026-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_remove_authlog_logs_authlo_usernam_fa5a0e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Dodaj'), ('update', 'Edytuj'), ('delete', 'Usuń'), ('approve', 'Zatwierdź'), ('reject', 'Odrzuć'), ('cancel', 'Anuluj')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_type',
            field=models.CharField(choices=[('user', 'Konto Użytkownika'), ('worker_profile', 'Profil Pracownika'), ('team', 'Zespół'), ('leave_request', 'Wniosek urlopowy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Ostrzeżenie'), ('critical', 'Krytyczne')], default='info', max_length=10),
        ),
    ]
