# Generated by Django 6.0.6 on 2026-08-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_authlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Logowanie udane'), ('login_failed', 'Logowanie nieudane'), ('incorrect_username', 'Brak użytkownika'), ('2fa_success', 'Weryfikacja 2FA udana'), ('2fa_failed', 'Niepoprawny kod 2FA'), ('logout', 'Wylogowanie'), ('access_denied_403', 'Odmowa dostępu'), ('ip_locked', 'IP zablokowane'), ('role_change', 'Zmiana roli'), ('password_changed', 'Zmiana hasła')], max_length=20),
        ),
    ]
